### ISSUE TITLE
Key binds screen has things configured wrong

### ISSUE THREAD

**Issue by User670** [26F-Studio/Techmino_Galaxy#28]
happened on the build from commit 6cc0d16117f523f6948519045a4c79bc15bcf5fa , Windows x64

![image](https://github.com/26F-Studio/Techmino_Galaxy/assets/22617255/20c93f64-31ec-4432-ab3c-fa4fae9c3c9a)

What I pressed was function 1 through 4 = A S D F, but this thing put every one of those keys one off, and there is a "skip" thing with no string

**Comment by MrZ626** [comment]
fixed
