### ISSUE TITLE
Half Clears can be made by clearing a Single on a player-made stack

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino_Galaxy#31]
https://github.com/26F-Studio/Techmino_Galaxy/assets/125081901/bb15af7e-34c9-4a54-b646-222d806d9580

Inconsistent with Techmino's HPC, when if it's a player-made stack, HPC only triggers after clearing 2+ lines.

If that's an intended behavior, this issue can be closed.

**Comment by MrZ626** [comment]
this part is WIP, I need more completed game modes to make attacking system make sense, so just ignore it now
