### ISSUE TITLE
Piano color scheme doesn't make sense

### ISSUE THREAD

**Issue by User670** [26F-Studio/Techmino_Galaxy#64]
![image](https://github.com/user-attachments/assets/96276714-0986-4227-8bdd-746769a9f8fd)
Current color scheme implies `<>?` is in the same octave as `QWE`

**Comment by MrZ626** [comment]
`<>?` share tone height with QWE so they share same color too

**Comment by User670** [comment]
Okay. Then make RTYU share color with QWE, else it's like RTYU is one octave higher from QWE

I think I expressed my point badly in my original issue text
